name: Java CI with Gradle

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Clear Gradle Cache
        run: rm -rf ~/.gradle/caches/

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Verify JAR file
        run: |
          ls -l ./build/libs/
          if [ ! -f "./build/libs/my-app-1.0-SNAPSHOT.jar" ]; then
            echo "JAR file not found!"
            exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: yaqbx/demo-app:latest
